export const modalConfig = {
  classNames: {
    popup: "ziadah-popup",
    modal: "ziadah-modal",
    modalContent: "modal-content",
    closeButton: "close",
    productsContainer: "products-container",
    product: "product",
    productImage: "product-image",
    productDetails: "product-details",
    addToCart: "add-to-cart",
    coupon: "coupon",
    copyCoupon: "copy-coupon",
    variantDropdown: "variant-dropdown",
    dropdownHeader: "dropdown-header",
    dropdownContent: "dropdown-content",
    variantCollapse: "variant-collapse",
    collapseHeader: "collapse-header",
    collapseContent: "collapse-content",
    chevronIcon: "chevron-icon",
    productAttribute: "product-attribute",
  },
  selectors: {
    modalContent: ".modal-content",
    closeButton: ".close",
    productsContainer: ".products-container",
    addToCart: ".add-to-cart",
    coupon: ".coupon",
    copyCoupon: ".copy-coupon",
    productAttribute: ".product-attribute",
  },
  dataAttributes: {
    productId: "data-product-id",
  },
};
